/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.com.ubam.proyectodulces.paneles;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.com.ubam.proyectodulces.catalogo.CatalogoCliente;
import mx.com.ubam.proyectodulces.clases.Cliente;

/**
 *
 * @author irvin
 */
public class PaginaCliente extends javax.swing.JPanel {
    
    CatalogoCliente cc = new CatalogoCliente();
    /**
     * Creates new form PaginaCliente
     */
    public PaginaCliente() {
        initComponents();
        llenartabla();           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FieldId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 102, -1, -1));

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 102, -1, -1));

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 102, -1, -1));

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableCliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 16, 347, 202));

        jLabel1.setText("Ventana Cliente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel2.setText("Ingresa id:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, -1, -1));
        add(FieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 28, 230, -1));

        jLabel3.setText("Ingresa Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 65, -1, -1));
        add(FieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 62, 208, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 102, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        int respuesta = JOptionPane.showConfirmDialog(null, "Deseas eliminar los productos" , "Aviso" , JOptionPane.YES_NO_OPTION);
        if(respuesta == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null, "Se han eliminado todos los productos");
            CatalogoCliente.listaCliente.clear();
            llenartabla();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        llenartabla();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombre = FieldNombre.getText();
        int id = Integer.parseInt(FieldId.getText());

        //Agregar Producto
        Cliente cliente = new Cliente(id, nombre);
        CatalogoCliente.agregarCliente(cliente);
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void limpiarTabla(){
        DefaultTableModel temp = (DefaultTableModel) TableCliente.getModel();
        int fila = TableCliente.getRowCount();
        for(int x = 0 ; fila > x ; x++)
            temp.removeRow(0);
        
    }
    public void limpiar(){
        FieldId.setText("");
        FieldNombre.setText("");
        FieldId.requestFocus();
    }
    public void llenartabla(){
        
        DefaultTableModel tm = new DefaultTableModel();
        tm.addColumn("Id");
        tm.addColumn("Nombre");
        
        List<Object[]> rows = new ArrayList<>();
            for(int i = 0 ; i < CatalogoCliente.getCatalogoClientes().size() ; i++){
                rows.add(new Object[]{CatalogoCliente.getCatalogoClientes().get(i).getIdCliente() 
                        , CatalogoCliente.getCatalogoClientes().get(i).getNombreCliente()});
            }
                for(Object[] row : rows){
                tm.addRow(row);
                }
                TableCliente.setModel(tm);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FieldId;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTable TableCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
