/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mx.com.ubam.proyectodulces.paneles;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.com.ubam.proyectodulces.catalogo.CatalogoCliente;
import mx.com.ubam.proyectodulces.catalogo.CatalogoDulces;
import mx.com.ubam.proyectodulces.catalogo.CatalogoVendedor;
import mx.com.ubam.proyectodulces.catalogo.DetalleVentas;
import mx.com.ubam.proyectodulces.catalogo.SesionVendedor;
import mx.com.ubam.proyectodulces.clases.Cliente;
import mx.com.ubam.proyectodulces.clases.DetalleVenta;
import mx.com.ubam.proyectodulces.clases.Dulce;
import mx.com.ubam.proyectodulces.ventanas.Ticket;

/**
 *
 * @author irvin
 */
public class PaginaCrearTicket extends javax.swing.JPanel {
    CatalogoCliente cc = new CatalogoCliente();
    CatalogoDulces cd = new CatalogoDulces();
    CatalogoVendedor cv = new CatalogoVendedor();
    SesionVendedor sv = new SesionVendedor();
    DetalleVentas dv = new DetalleVentas();
            int numVenta = 0;
    /**
     * Creates new form PaginaCrearTicket
     */
    public PaginaCrearTicket() {
        initComponents();
        cargarDatosDulce();
        cargarDatosCliente();
        getVendedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FieldNumVenta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxCliente = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxDulce = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableDetalleVentas = new javax.swing.JTable();
        LabelVendedor = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FieldCantidad = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ventana de Ventas");

        jLabel2.setText("Numero de Venta:");

        FieldNumVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNumVentaActionPerformed(evt);
            }
        });

        jButton1.setText("Actualizar Datos");

        jLabel3.setText("Cliente");

        ComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Vendedor:");

        jLabel5.setText("Dulce:");

        ComboBoxDulce.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Detalle de Venta");

        TableDetalleVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero de Venta", "Cliente", "Vendedor", "Dulce", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableDetalleVentas.setEnabled(false);
        jScrollPane2.setViewportView(TableDetalleVentas);

        LabelVendedor.setText(".");

        jLabel7.setText("Cantidad:");

        jButton2.setBackground(new java.awt.Color(102, 255, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Agregar Venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Crear Ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldNumVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldCantidad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(57, 57, 57)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(LabelVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxDulce, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FieldNumVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel7)
                    .addComponent(FieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(LabelVendedor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ComboBoxDulce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(FieldNumVenta.getText().isEmpty()){
            numVenta++;
        }else{
            numVenta = Integer.parseInt(FieldNumVenta.getText());
        }
        if(FieldCantidad.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debes rellenar todos los campos para realizar la venta");
        }else{
        int cantidad = Integer.parseInt(FieldCantidad.getText());
        String Cliente = (String)ComboBoxCliente.getSelectedItem();
        String Dulce = (String)ComboBoxDulce.getSelectedItem();
        String Vendedor = SesionVendedor.getVendedor();
        
        DetalleVenta detalle = new DetalleVenta(numVenta, cantidad , ventas() , getDulce() , Vendedor , Cliente );
        DetalleVentas.agregarDetalleVenta(detalle);
        llenartabla();
        borrar();
        
        }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void FieldNumVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNumVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNumVentaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Ticket().show();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    public Dulce getDulce(){
         for(Dulce d : CatalogoDulces.listaDulces)
            if(d.getPresentacion() == ComboBoxDulce.getSelectedItem()){
                return d;
            }
            return null;
    }
    public void cargarDatosDulce(){
        ComboBoxDulce.removeAllItems();
            for(Dulce d : CatalogoDulces.listaDulces)
                ComboBoxDulce.addItem(d.getPresentacion());
    }
    public void cargarDatosCliente(){
        ComboBoxCliente.removeAllItems();
            for(Cliente c : CatalogoCliente.listaCliente)
                ComboBoxCliente.addItem(c.getNombreCliente());
    }
    public void getVendedor(){
        LabelVendedor.setText(SesionVendedor.getVendedor());
    }
    public double ventas(){
        double cantidad = Double.parseDouble(FieldCantidad.getText());
        double preciobase = 0;
        String dulce = (String)ComboBoxDulce.getSelectedItem();
        for(Dulce d : CatalogoDulces.listaDulces){
            if(dulce.equals(d.getPresentacion())){
                preciobase = d.getPrecioBase();
            }
        }
        return cantidad * preciobase;
    }
    public void llenartabla(){
        
        
        DefaultTableModel tm = new DefaultTableModel();
        tm.addColumn("Numero de Venta");
        tm.addColumn("Cliente");
        tm.addColumn("Vendedor");
        tm.addColumn("Dulce");
        tm.addColumn("Cantidad");
        tm.addColumn("Total");
        
        List<Object[]> rows = new ArrayList<>();
            for( int i =0 ; i < DetalleVentas.getDetalleVenta().size() ; i++){
                rows.add(new Object[] { DetalleVentas.detalleVenta.get(i).getNumDetalleVenta() , DetalleVentas.detalleVenta.get(i).getCliente() ,
                                        DetalleVentas.detalleVenta.get(i).getVendedor() , DetalleVentas.detalleVenta.get(i).getDulce().getPresentacion() ,
                                        DetalleVentas.detalleVenta.get(i).getCantidad() , DetalleVentas.detalleVenta.get(i).getImporte() });  
            }
                      
                for(Object[] row : rows){
                tm.addRow(row);
                }
                TableDetalleVentas.setModel(tm);
    }
    public void borrar(){
        FieldCantidad.setText("");
        FieldCantidad.requestFocus();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCliente;
    private javax.swing.JComboBox<String> ComboBoxDulce;
    private javax.swing.JTextField FieldCantidad;
    private javax.swing.JTextField FieldNumVenta;
    private javax.swing.JLabel LabelVendedor;
    private javax.swing.JTable TableDetalleVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
